// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Observation struct {
	Time           time.Time `json:"time"`
	StationID      string    `json:"station_id"`
	Parameter      int32     `json:"parameter"`
	ParameterName  string    `json:"parameter_name"`
	Unit           string    `json:"unit"`
	ResolutionTime int32     `json:"resolution_time"`
	Value          *float64  `json:"value"`
	Quality        *int32    `json:"quality"`
	Correction     *int32    `json:"correction"`
	IngestedAt     time.Time `json:"ingested_at"`
}

type Station struct {
	StationID string    `json:"station_id"`
	Name      string    `json:"name"`
	RiverName *string   `json:"river_name"`
	Latitude  *float64  `json:"latitude"`
	Longitude *float64  `json:"longitude"`
	Masl      *float64  `json:"masl"`
	UpdatedAt time.Time `json:"updated_at"`
}
