// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const insertObservation = `-- name: InsertObservation :exec
INSERT INTO observations (
    time, station_id, parameter, parameter_name, unit, resolution_time, value, quality, correction
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (station_id, parameter, resolution_time, time) DO UPDATE SET
    value      = EXCLUDED.value,
    quality    = EXCLUDED.quality,
    correction = EXCLUDED.correction
`

type InsertObservationParams struct {
	Time           time.Time `json:"time"`
	StationID      string    `json:"station_id"`
	Parameter      int32     `json:"parameter"`
	ParameterName  string    `json:"parameter_name"`
	Unit           string    `json:"unit"`
	ResolutionTime int32     `json:"resolution_time"`
	Value          *float64  `json:"value"`
	Quality        *int32    `json:"quality"`
	Correction     *int32    `json:"correction"`
}

// Insert an observation; on conflict, update the value/quality/correction so
// re-polling overlapping time windows is idempotent.
func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.db.Exec(ctx, insertObservation,
		arg.Time,
		arg.StationID,
		arg.Parameter,
		arg.ParameterName,
		arg.Unit,
		arg.ResolutionTime,
		arg.Value,
		arg.Quality,
		arg.Correction,
	)
	return err
}

const latestObservations = `-- name: LatestObservations :many
SELECT DISTINCT ON (station_id, parameter)
    time, station_id, parameter, parameter_name, unit, resolution_time, value, quality, correction, ingested_at
FROM observations
WHERE station_id = $1
ORDER BY station_id, parameter, time DESC
`

// Most recent observation for each parameter at a station (one row per parameter).
func (q *Queries) LatestObservations(ctx context.Context, stationID string) ([]Observation, error) {
	rows, err := q.db.Query(ctx, latestObservations, stationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.Time,
			&i.StationID,
			&i.Parameter,
			&i.ParameterName,
			&i.Unit,
			&i.ResolutionTime,
			&i.Value,
			&i.Quality,
			&i.Correction,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStations = `-- name: ListStations :many
SELECT station_id, name, river_name, latitude, longitude, masl, updated_at
FROM stations
ORDER BY station_id
`

func (q *Queries) ListStations(ctx context.Context) ([]Station, error) {
	rows, err := q.db.Query(ctx, listStations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Station
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.StationID,
			&i.Name,
			&i.RiverName,
			&i.Latitude,
			&i.Longitude,
			&i.Masl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationsByStation = `-- name: ObservationsByStation :many
SELECT time, station_id, parameter, parameter_name, unit, resolution_time, value, quality, correction, ingested_at
FROM observations
WHERE station_id = $1
  AND parameter = $2
  AND time >= $3
  AND time <= $4
ORDER BY time DESC
`

type ObservationsByStationParams struct {
	StationID string    `json:"station_id"`
	Parameter int32     `json:"parameter"`
	Time      time.Time `json:"time"`
	Time_2    time.Time `json:"time_2"`
}

// Observations for one station and parameter within an inclusive time range,
// newest first.
func (q *Queries) ObservationsByStation(ctx context.Context, arg ObservationsByStationParams) ([]Observation, error) {
	rows, err := q.db.Query(ctx, observationsByStation,
		arg.StationID,
		arg.Parameter,
		arg.Time,
		arg.Time_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.Time,
			&i.StationID,
			&i.Parameter,
			&i.ParameterName,
			&i.Unit,
			&i.ResolutionTime,
			&i.Value,
			&i.Quality,
			&i.Correction,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStation = `-- name: UpsertStation :exec

INSERT INTO stations (station_id, name, river_name, latitude, longitude, masl, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (station_id) DO UPDATE SET
    name       = EXCLUDED.name,
    river_name = EXCLUDED.river_name,
    latitude   = EXCLUDED.latitude,
    longitude  = EXCLUDED.longitude,
    masl       = EXCLUDED.masl,
    updated_at = now()
`

type UpsertStationParams struct {
	StationID string   `json:"station_id"`
	Name      string   `json:"name"`
	RiverName *string  `json:"river_name"`
	Latitude  *float64 `json:"latitude"`
	Longitude *float64 `json:"longitude"`
	Masl      *float64 `json:"masl"`
}

// sqlc query definitions. Each `-- name:` block generates a type-safe Go method
// in internal/db (regenerate with `make sqlc`).
// Insert or update a station's metadata, keyed by station_id.
func (q *Queries) UpsertStation(ctx context.Context, arg UpsertStationParams) error {
	_, err := q.db.Exec(ctx, upsertStation,
		arg.StationID,
		arg.Name,
		arg.RiverName,
		arg.Latitude,
		arg.Longitude,
		arg.Masl,
	)
	return err
}
